services:
  postgres:
    container_name: postgres_first
    image: postgres
    restart: always
    environment:
      POSGRES_DB: pet_home
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - 5434:5432
    volumes:
    - postgres-data:/var/lib/postgres/data
  
  seq:
    image: datalust/seq:latest
    container_name: seq_first
    restart: always
    environment:
    - ACCEPT_EULA=Y
    ports: 
    - 5341:5341
    - 8081:80
    volumes:
    - postgres-data:/var/lib/postgres/data

  minio:
    image: minio/minio
    container_name: minio_first
    restart: always
    ports:
    - 9000:9000
    - 9001:9001
    volumes:
    - minio_data:/data
    command: server /data --console-address ":9001"


volumes:
  postgres-data:
  minio_data:
    