services:
  web:
    container_name: web
    image: smirnyy82/pethome-backend:1.0
    ports:
        - "8080:8080"
    restart: always
    depends_on: 
        - postgres
        - seq
        - minio
    environment:
        - ASPNETCORE_ENVIRONMENT=Docker

  frontend:
    container_name: front
    image: pethome.frontend:latest
    ports:
        - "8888:33445"
    restart: always 

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_main
    hostname: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
  
  nginx:
    container_name: nginx_main
    image: nginx:latest
    ports:
     - "80:80"
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
     - web
    restart: always

  postgres:
    container_name: postgres_main
    image: postgres
    restart: always
    environment:
      POSGRES_DB: pet_home
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - "5434:5432"
    volumes:
    - postgres-data:/var/lib/postgres/data 
     
  seq:
    image: datalust/seq:latest
    container_name: seq_main
    restart: always
    environment:
    - ACCEPT_EULA=Y
    ports: 
    - "5341:5341"
    - "8081:80"
    volumes:
    - postgres-data:/var/lib/postgres/data

  minio:
    image: minio/minio
    container_name: minio_main
    restart: always
    ports:
    - "9000:9000"
    - "9001:9001"
    volumes:
    - minio_data:/data
    command: server /data --console-address ":9001"

  mongodb:
    image: mongo
    container_name: mongo_main
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: mongo
        MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
    - 27017:27017
    volumes:
    - mongo_data:/data/db

  elasticsearch:
    # image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    image: elasticsearch:8.7.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200" 
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: always 

  kibana:
    image: kibana:8.7.1
    container_name: kibana
    environment: 
      - ELASTICSEARCH_URL=http://localhost:9200  
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: always
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - "./prometheus.yml:/etc/prometheus.yml" 
      - "prometheus_data:/prometheus" 
    ports:
      - "9090:9090"
   
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
      # increases the log level from info to debug
      - GF_LOG_LEVEL=debug
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - 'grafana_storage:/var/lib/grafana'

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379" 
    volumes:
      - "redis_data:/data" 
    
  jaeger:
    image: ${REGISTRY:-}jaegertracing/jaeger:${JAEGER_VERSION:-latest}
    restart: always
    container_name: jaeger
    ports:
       - "5775:5775"   
       - "6831:6831/udp"   
       - "6832:6832/udp"   
       - "5778:5778"    
       - "16686:16686"  
       - "14250:14250"  
       - "14268:14268"  
       - "9411:9411"    
    environment:
      - LOG_LEVEL=debug 

volumes:
  postgres-data:
  minio_data:
  mongo_data:
  rabbitmq_data: 
  elasticsearch_data:   
  prometheus_data:
  grafana_storage:  
  redis_data: