name: Base Build ASP.NET Core

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: 🏗 Build
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🛠 Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: 📦 Restore dependencies
        run: dotnet restore src/Accounts/PetHome.Accounts.Domain/PetHome.Accounts.Domain.csproj

      - name: 🏗 Build
        run: dotnet build src/Accounts/PetHome.Accounts.Domain/PetHome.Accounts.Domain.csproj --configuration Release --no-restore 
       